version: "3.9"
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: iep_ally
    ports:
      - "5432:5432"
    volumes:
      - ./docker-data/postgres:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  api:
    build:
      context: .
      dockerfile: infra/docker/api.Dockerfile
    environment:
      NODE_ENV: development
      PORT: 8080
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/iep_ally
      REDIS_URL: redis://redis:6379
      JWT_SECRET: dev-secret
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"

  web:
    build:
      context: .
      dockerfile: infra/docker/web.Dockerfile
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_BASE_URL: http://localhost:8080
    depends_on:
      - api
    ports:
      - "3000:3000"

  worker:
    build:
      context: .
      dockerfile: infra/docker/worker.Dockerfile
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/iep_ally
      REDIS_URL: redis://redis:6379
    depends_on:
      - postgres
      - redis

volumes:
  postgres:

