version: "3.9"
services:
  minio:
    image: minio/minio:RELEASE.2024-10-02T17-50-41Z
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./docker-data/minio:/data
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: iep_ally
    ports:
      - "5432:5432"
    volumes:
      - ./docker-data/postgres:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  api:
    build:
      context: .
      dockerfile: infra/docker/api.Dockerfile
    environment:
      NODE_ENV: development
      PORT: 8080
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/iep_ally
      REDIS_URL: redis://redis:6379
      JWT_SECRET: dev-secret
      S3_ENDPOINT: http://minio:9000
      S3_BUCKET: iep-ally
      S3_ACCESS_KEY_ID: minioadmin
      S3_SECRET_ACCESS_KEY: minioadmin
      MAIL_HOST: mailhog
      MAIL_PORT: 1025
      MAIL_FROM: no-reply@iep-ally.local
      ADMIN_API_KEY: dev-admin
      INTERNAL_API_KEY: dev-internal
    depends_on:
      - postgres
      - redis
      - minio
    ports:
      - "8080:8080"

  web:
    build:
      context: .
      dockerfile: infra/docker/web.Dockerfile
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_BASE_URL: http://localhost:8080
    depends_on:
      - api
    ports:
      - "3000:3000"

  worker:
    build:
      context: .
      dockerfile: infra/docker/worker.Dockerfile
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/iep_ally
      REDIS_URL: redis://redis:6379
      S3_ENDPOINT: http://minio:9000
      S3_BUCKET: iep-ally
      S3_ACCESS_KEY_ID: minioadmin
      S3_SECRET_ACCESS_KEY: minioadmin
      INTERNAL_API_KEY: dev-internal
      API_URL: http://api:8080
    depends_on:
      - postgres
      - redis
      - minio
  
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"
      - "8025:8025"
volumes:
  postgres:
