name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: joslyn_ai
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: pnpm install

      - name: Run Prisma migrations
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/joslyn_ai
        run: pnpm --filter @joslyn-ai/db migrate

      - name: Typecheck
        run: pnpm -r typecheck

      - name: Build
        run: pnpm -r build

      - name: Run API unit tests
        run: pnpm --filter @joslyn-ai/api test

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install worker test dependencies
        run: pip install pytest

      - name: Run worker unit tests
        env:
          PYTHONPATH: services/worker/src
        run: python -m pytest services/worker/tests
